services:
  latex:
    container_name: LaTeX
    tty: true
    restart: always
    build:
      args:
        workdir: "latex"
        username: ${USER}
      context: ./.devcontainer/
      dockerfile: Dockerfile
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - ./docs:/root/latex/docs